# Note that in original FLAVA paper, only Logistic Regression numbers were provided for image datasets.
_target_: definitions.FLAVAArguments
training:
  _target_: definitions.TrainingArguments
  lightning:
    max_steps: 20935
    gpus: -1
    progress_bar_refresh_rate: 50
    val_check_interval: 100
    num_sanity_val_steps: 0
  seed: -1
  batch_size: 32
  num_workers: 4
  learning_rate: 1e-5
  adam_eps: 1e-8
  adam_weight_decay: 1e-2
  warmup_steps: 1256
  strategy: ddp


datasets:
  _target_: definitions.TrainingDatasetsInfo
  selected:
  - image
  num_classes: 2
  image:
    _target_: definitions.TrainingSingleDatasetInfo
    train:
      - _target_: definitions.TorchVisionDatasetInfo
        key: RenderedSST2
